--- #YAML:1.0
name:                WWW-Mechanize-Pluggable
version:             1.05
abstract:            A WWW::Mechanize that's custmomizable via plugins
license:             ~
author:              
    - Joe McMahon <mcmahon@yahoo-inc.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Carp:                          0
    Data::Dump::Streamer:          0
    File::Temp:                    0
    FindBin:                       0
    HTML::Form:                    1.038
    HTML::HeadParser:              0
    HTML::TokeParser:              2.28
    HTTP::Daemon:                  0
    HTTP::Request:                 1.3
    HTTP::Status:                  0
    LWP:                           5.76
    LWP::UserAgent:                2.024
    Module::Pluggable:             0
    Test::Exception:               0.2
    Test::More:                    0.34
    URI:                           1.25
    URI::file:                     0
    URI::URL:                      0
    WWW::Mechanize:                1.12
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
